---
ansible:
  group_vars:
    all:
      redmine_customize_language:
        ja:
          setting_app_title: タイトル
          project_module_documents: ドキュメント
          project_module_news: お知らせ
          label_document: ドキュメント
          label_document_new: 新しいドキュメント
          label_document_plural: ドキュメント
          label_document_added: ドキュメントの追加
          label_news: お知らせ
          label_news_new: お知らせを追加
          label_news_plural: お知らせ
          label_news_latest: 最新のお知らせ
          label_news_view_all: すべてのお知らせを表示
          label_news_added: お知らせの追加
          label_news_comment_added: お知らせへのコメント追加
          label_roadmap: マイルストーン
          label_in_less_than: n日後、以前
          label_in_more_than: n日後、以降
          label_in: n日後
          label_less_than_ago: n日前、以降
          label_more_than_ago: n日前、以前
          label_ago: n日前
          label_in_the_next_days: 今後n日以内
          label_in_the_past_days: 過去n日以内
          field_is_in_roadmap: チケットをマイルストーンに表示する
          enumeration_doc_categories: ドキュメントカテゴリ
          permission_add_documents: ドキュメントの追加
          permission_edit_documents: ドキュメントの編集
          permission_delete_documents: ドキュメントの削除
          permission_view_documents: ドキュメントの閲覧
          permission_view_news: お知らせの閲覧
          permission_manage_news: お知らせの管理
          permission_comment_news: お知らせへのコメント
          default_doc_category_user: ユーザーマニュアル
          default_doc_category_tech: 仕様書
          default_tracker_feature: 機能追加
          default_tracker_support: 保守
          default_issue_status_new: 未対応
          default_issue_status_in_progress: 対応中
          default_issue_status_resolved: 対応済み
          default_issue_status_feedback: 差し戻し
          default_issue_status_closed: 完了
          default_issue_status_rejected: 却下
          default_priority_low: 低い
          default_priority_normal: 普通
          default_priority_high: 高い
          default_priority_urgent: 緊急
          default_priority_immediate: 至急
      redmine_themes:
        - name: farend_fancy
          repo: "https://github.com/farend/redmine_theme_farend_fancy.git"
        - name: farend_basic
          repo: "https://github.com/farend/redmine_theme_farend_basic.git"
      redmine_plugins:
        # Githubから取得
        - name: view_customize
          repo: "https://github.com/onozaty/redmine-view-customize.git"
          directory: view_customize
        - name: issue_templates
          repo: "https://github.com/akiko-pusu/redmine_issue_templates.git"
        - name: slack
          repo: "https://github.com/sciyoshi/redmine-slack.git"
        # URLから取得
        - name: easy_gantt
          url: "http://www.easyredmine.com/packages/EasyGanttFree.zip"
          # 展開先ディレクトリ名(テスト用)
          directory: easy_gantt
        # ファイルのアップロード
        - name: agile
          file: ~/Downloads/redmine/redmine_agile-1_4_6-light.zip
          # 展開先ディレクトリ名(テスト用)
          directory: redmine_agile
        - name: checklists
          file: ~/Downloads/redmine/redmine_checklists-3_1_11-light.zip
          # 展開先ディレクトリ名(テスト用)
          directory: redmine_checklists
      redmine_send_reminders_cron_job:
        enabled: yes
        params:
          - 'days=7'
        hour: 9
        minute: 0
      redmine_receive_imap_cron_job:
        enabled: yes
        params:
          - "username=imap_acount"
          - "password=imap_password"
        hour: "*"
        minute: "*/5"
      redmine_receive_pop3_cron_job:
        enabled: yes
        params:
          - "username=pop3_acount"
          - "password=pop3_password"
        hour: "*"
        minute: "*/5"
      redmine_puma_cfg:
        bind: "unix:///opt/redmine/tmp/redmine.sock"
        pidfile: "/opt/redmine/tmp/redmine.pid"
        state_path: "/opt/redmine/tmp/redmine.state"
        stdout_redirect:
          stdout: "/opt/redmine/log/stdout.log"
          stderr: "/opt/redmine/log/stderr.log"
          append: yes
        quiet: yes
        threads:
          min: 0
          max: 16
        workers: 2
        prune_bundler: no
        preload_app: yes
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: stretch
      box: histudy/stretch
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 1024
        cpus: 1
  instances:
    - name: redmine
      ansible_groups:
        - molecule
verifier:
  name: serverspec
