---
galaxy_info:
  role_name: redmine
  author: yoshiaki tanaka
  description: setup redmine
  license: Apache
  min_ansible_version: "2.10"
  platforms:
    - name: Debian
      versions:
        - bullseye
dependencies: []
